### ISSUE TITLE
About and Contact pages give me an Error 404 from Landing Page

### ISSUE THREAD

**Issue by jeanfboueri** [raudio-project/raudio-project.github.io#14]
![Screenshot from 2022-03-31 15-55-21](https://user-images.githubusercontent.com/75325848/161138814-3e8958d1-354d-49a2-86b9-5be683561938.png)
![Screenshot from 2022-03-31 15-55-58](https://user-images.githubusercontent.com/75325848/161138867-5b2c95a5-0e04-4225-aa90-881bbcd40b01.png)
![Screenshot from 2022-03-31 15-56-03](https://user-images.githubusercontent.com/75325848/161138883-e004a698-dcdb-49e9-bb2b-bde6ccd153aa.png)

**Comment by simonrodrig** [comment]
The about page issue should be addressed now with #10 

contact page is WIP
